openapi: 3.0.0
paths:
  /api/v1/auth/login:
    post:
      operationId: AuthController_login
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginDto'
      responses:
        '201':
          description: ''
      summary: Login con username y password
      tags: &ref_0
        - Auth
  /api/v1/auth/change-password:
    post:
      operationId: AuthController_changePassword
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChangePasswordDto'
      responses:
        '201':
          description: ''
      security:
        - bearer: []
      summary: Cambiar contraseña (protegido por JWT)
      tags: *ref_0
  /api/v1/prosper/funds:
    post:
      operationId: ProsperController_createFund
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateFundDto'
      responses:
        '201':
          description: ''
      security: &ref_1
        - bearer: []
      tags: &ref_2
        - Prosper
  /api/v1/prosper/tokens/mint:
    post:
      operationId: ProsperController_mint
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MintDto'
      responses:
        '201':
          description: ''
      security: *ref_1
      tags: *ref_2
  /api/v1/prosper/assets:
    get:
      operationId: ProsperController_assets
      parameters: []
      responses:
        '200':
          description: ''
      security: *ref_1
      tags: *ref_2
  /api/v1/prosper/users/new:
    post:
      operationId: ProsperController_createUser
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewUserDto'
      responses:
        '201':
          description: ''
      security: *ref_1
      tags: *ref_2
  /api/v1/prosper/users/deposit:
    post:
      operationId: ProsperController_deposit
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DepositDto'
      responses:
        '201':
          description: ''
      security: *ref_1
      tags: *ref_2
  /api/v1/prosper/users/transfer:
    post:
      operationId: ProsperController_transfer
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransferDto'
      responses:
        '201':
          description: ''
      security: *ref_1
      tags: *ref_2
  /api/v1/prosper/users/retire:
    delete:
      operationId: ProsperController_retire
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DepositDto'
      responses:
        '200':
          description: ''
      security: *ref_1
      tags: *ref_2
  /api/v1/prosper/users/{prosperId}/balances:
    get:
      operationId: ProsperController_userBalances
      parameters:
        - name: prosperId
          required: true
          in: path
          schema:
            type: string
      responses:
        '200':
          description: ''
      security: *ref_1
      tags: *ref_2
  /api/v1/prosper/users/{prosperId}/transactions:
    get:
      operationId: ProsperController_userTransactions
      parameters:
        - name: prosperId
          required: true
          in: path
          schema:
            type: string
        - name: limit
          required: false
          in: query
          description: Numero de Reportes por pagina
          schema:
            example: 10
            type: number
        - name: page
          required: false
          in: query
          description: Pagina del reporte
          schema:
            example: 1
            type: number
        - name: createdAt
          required: false
          in: query
          description: 'Fecha de creación (ISO), ejemplo: "2024-01-01"'
          schema:
            type: string
        - name: status
          required: false
          in: query
          description: 'Estado de la transacción, ejemplo: Pendiente, Completada, Rechazada'
          schema:
            type: string
        - name: txType
          required: false
          in: query
          description: >-
            Tipo de transacciónejemplo: Mint, Depósito, Retiro, Transferencia,
            Staking
          schema:
            type: string
      responses:
        '200':
          description: ''
      security: *ref_1
      tags: *ref_2
info:
  title: APIs Prosper - Stellar Protocol
  description: APIs Prosper - Stellar Protocol documentation
  version: '2.0'
  contact: {}
tags: []
servers: []
components:
  securitySchemes:
    bearer:
      scheme: bearer
      bearerFormat: JWT
      type: http
  schemas:
    LoginDto:
      type: object
      properties:
        username:
          type: string
          description: Nombre de usuario
          example: usuario
        password:
          type: string
          description: Contraseña
          example: miPassword123
      required:
        - username
        - password
    ChangePasswordDto:
      type: object
      properties:
        oldPassword:
          type: string
          description: Contraseña antigua
          example: oldPassword
        newPassword:
          type: string
          description: Contraseña nueva
          example: newPassword
      required:
        - oldPassword
        - newPassword
    CreateFundDto:
      type: object
      properties:
        initialAmount:
          type: string
          description: Cantidad inicial a emitir
        homeDomain:
          type: string
          description: Dominio home para SEP-10 / well-known
        prosperTxId:
          type: string
          description: Identificador de la transacción en Prosper
    MintDto:
      type: object
      properties:
        amount:
          type: string
        reason:
          type: string
        prosperTxId:
          type: string
      required:
        - amount
        - prosperTxId
    NewUserDto:
      type: object
      properties:
        userReferenceId:
          type: string
        prosperTxId:
          type: string
          description: Identificador de la transacción en Prosper
      required:
        - userReferenceId
        - prosperTxId
    DepositDto:
      type: object
      properties:
        prosperTxId:
          type: string
          description: Identificador de la transacción en Prosper
        amount:
          type: string
        userReferenceId:
          type: string
          description: >-
            Identificador de referencia del usuario en el sistema externo,
            OPCIONAL
        address:
          type: string
          description: >-
            Dirección de la wallet del usuario, valor interno del protocolo,
            OPCIONAL
      required:
        - prosperTxId
        - amount
    TransferMetadataDto:
      type: object
      properties:
        price:
          type: number
        currency:
          type: string
        contractRef:
          type: string
        transferType:
          type: string
    TransferDto:
      type: object
      properties:
        amount:
          type: string
        fromUserId:
          type: string
        toUserId:
          type: string
        prosperTxId:
          type: string
          description: Identificador de la transacción en Prosper
        metadata:
          $ref: '#/components/schemas/TransferMetadataDto'
      required:
        - amount
        - fromUserId
        - toUserId
        - prosperTxId
